GET http://localhost:8080/users
Accept: application/json

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Edward",
  "age": 23,
  "countryOfResidence": "RF"
}

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Rauf",
  "age": 22,
  "countryOfResidence": "RF"
}

###
GET http://localhost:8080/users/Edward
Accept: application/json

###
PATCH http://localhost:8080/users/Edward
Content-Type: application/json

{
  "name": "Ernesto",
  "age": 22,
  "countryOfResidence": "RF"
}